---
# Here you can add variables that will be available for all hosts.
region: northeurope
resource_group: BTH-kmom01-KRMN18-8c4b74 # Change me
domain_name: manczak.me # Change me

root_user: azureuser

vmtags:
    StudentId: "krmn18" # Change me


pub_ssh_key_location: /home/kryman/.ssh/azure_ci.pub # Change me, your local ssh key!

# My own variables:
deploy_user: deploy
my_ip: "{{ lookup('env', 'MY_IP') }}"